services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    restart: always
    command: npm run dev
    ports:
      - "3000:3000" 
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    user: root
  
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    # restart: always
    # command: python uvicorn src/main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code