services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    restart: always
    command: npm run dev
    ports:
      - "3000:3000" 
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    user: root
  
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    # restart: always
    # command: python uvicorn src/main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code

  postgres:
    image: "postgres:16" # Updated to a valid version
    restart: always
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_USER: myuser 
      POSTGRES_PASSWORD: mypassword   
      POSTGRES_DB: myPoetry       
    volumes:
      - PoetryVolume:/var/lib/postgresql/data/

volumes:
  PoetryVolume: